### ISSUE TITLE
not disabled after restarting obsidian

### ISSUE THREAD

**Issue by xverbatim1971** [nagi1999a/obsidian-focus-plugin#12]
hello,
thanks again for the improvement of the plugin :-)

I still noticed when I activate the plugin via the toogle button and I turn it off.
the next time i start obsidian it is on again, even though i turned it off :-)
best regards
Thomas

**Comment by nagi1999a** [comment]
Oh, sorry that’s my fault! I didn’t save state for each session, I will fix this this weekend! Thanks for discovering this bug!

**Comment by nagi1999a** [comment]
Hello @xverbatim1971!
I have released the new version 1.3.2, which makes the toggle stateful. Please give it a try. Thanks for discovering the bug!

**Comment by nagi1999a** [comment]
Looks like the bug is fixed! I am going to close the issue, if there is any unexpected behavior, please feel free to leave comments!
