### ISSUE TITLE
Don't focus on fold

### ISSUE THREAD

**Issue by lucashabersaat** [nagi1999a/obsidian-focus-plugin#13]
Hi, great plugin I love it! :)

One little thing, though. I have the `Editor > Display > Fold heading` option enabled and it would be great, if it wouldn't focus when I fold (collapse) a heading, i.e. clicking on the arrow left of the header to 'close' it. 
On expand it's just fine when it focuses on the heading.

This particularly happens, when I fold a heading which is not in focus. 

Thanks for considering!
Best regards,
Lucas

**Comment by nagi1999a** [comment]
Hello, @lucashabersaat!
I'm glad that you like the plugin! Thanks for discovering the bug. I have potentially fixed it today and released the new version 1.3.2.
Please do an update and leave a comment if the bug still exists!

**Comment by lucashabersaat** [comment]
Great, works as expected! 
Thanks for the swift fix.

**Comment by nagi1999a** [comment]
Thanks for testing! I will close the issue now.
