### ISSUE TITLE
Focus on heading and its "children" also when clicking a "child" of the heading

### ISSUE THREAD

**Issue by bkis** [nagi1999a/obsidian-focus-plugin#5]
I understand that highlighting other (single) blocks isn't supported (yet), but it'd still be good if one wouldn't have to click the actual heading to trigger the focus. Instead, triggering on a click on any block that is a "child" (nothing is really a child of a heading - except inline blocks - but from a document semantic point of view...) of the respective heading would be very convenient.

**Comment by nagi1999a** [comment]
Thanks for your suggestion, it is a great idea!
I already have some preliminary thoughts on how to implement this, but it may take some time since I am a little busy recently.
I will try my best to realize it in one month!

**Comment by nagi1999a** [comment]
Hello!
I have released version 1.2.0, this version includes the support of the feature. Please give it a try!
If it has any bug or unexpected behavior, please reply in the thread!

**Comment by nagi1999a** [comment]
Looks like everything works as expected, I am going to close the issue!

**Comment by bkis** [comment]
Sorry I didn't find the time to test this and report back. It's great that you implemented it though!

**Comment by nagi1999a** [comment]
Thanks a lot for your appreciation and all your contribution to the project!
