### ISSUE TITLE
Focus doesn't trigger when clicking an inline block inside a heading

### ISSUE THREAD

**Issue by bkis** [nagi1999a/obsidian-focus-plugin#6]
If a heading contains an inline block (inline code, emphasis, strikethrough, ...), you have to click *outside* of said inline block to trigger the focus. Take this example:

```md
# foo
bar

# `foo`
bar

# *foo*
bar

# ~~foo~~
bar
``` 

It works as expected for the first heading, but not with the other three. The plugin should simply check if the clicked block's parent is a heading, I guess.

**Comment by nagi1999a** [comment]
Hello @bkis! Thanks again for identifying and giving a such great fix!
