### ISSUE TITLE
can i adjust the opacity

### ISSUE THREAD

**Issue by imshenwei** [nagi1999a/obsidian-focus-plugin#9]
as my title
can i adjust opactiy?

**Comment by nagi1999a** [comment]
Yes! Please follow the instructions under the [Style Settings](https://github.com/nagi1999a/obsidian-focus-plugin#style-settings) section to get it to work.

After installing the [Obsidian Style Settings Plugin](https://github.com/mgmeyers/obsidian-style-settings), you may need to restart obsidian to make it show in the settings tab. It will look like the following:
![Screenshot_20220910_115021](https://user-images.githubusercontent.com/49529145/189467506-67a196f6-0ed7-4766-804c-94bc082c440c.png)
Please try and leave a comment if you encounter any problems, thank you!

**Comment by imshenwei** [comment]
leave with a big big tumb up
have completed the adjust really quick!!!
